INSERT INTO users (username, email, passHash) VALUES ('K9Fenrir', 'k9fenrir@gmail.com', '$2a$10$4yO6PJRYK1D0A32rrnHCP.C6lak5d8zoxUfG4OqenxTOIXMofxYce');
INSERT INTO users (username, email, passHash) VALUES ('Heindell', 'heindell.lemuen@gmail.com', '$2a$10$4yO6PJRYK1D0A32rrnHCP.C6lak5d8zoxUfG4OqenxTOIXMofxYce');
INSERT INTO users (username, email, passHash) VALUES ('Xelphos', 'xelphos@xelphos.com', '$2a$10$4yO6PJRYK1D0A32rrnHCP.C6lak5d8zoxUfG4OqenxTOIXMofxYce');
INSERT INTO tag (id, description, type) VALUES ('F-R95', 'Image by F-R95', 'artist');
INSERT INTO tag (id, description, type) VALUES ('Hioshiru', 'Image by Hioshiru', 'artist');
INSERT INTO tag (id, description, type) VALUES ('canine', 'Contains species: canine', 'species');
INSERT INTO tag (id, description, type) VALUES ('human', 'Contains species: human', 'species');
INSERT INTO tag (id, description, type) VALUES ('feline', 'Contains species: feline', 'species');
INSERT INTO tag (id, description, type) VALUES ('standing', 'One or more people are standing', 'general');
INSERT INTO tag (id, description, type) VALUES ('outdoors', 'The image is taking place outside', 'general');
INSERT INTO tag (id, description, type) VALUES ('hat', 'There is a hat in the image', 'general');
INSERT INTO tag (id, description, type) VALUES ('window', 'There is a window in the image', 'general');
INSERT INTO tag (id, description, type) VALUES ('table', 'There is a table in the image', 'general');